name: google_places_dialog
description: A package to show a dialog with google places autocomplete.
version: 0.2.1
homepage: https://github.com/manuelperez96/google_places_dialog
repository: https://github.com/manuelperez96/google_places_dialog

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_debouncer: ^1.3.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
